name: "Hello Python workflow"

on: push

jobs:
  run_python:
    name: "Show Python version"
    runs-on: ubuntu-latest
    steps:
      - run: python --version

  run_specific_python:
    name: "Rune Python 3.13"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python --version