name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Run tests with Python 3.13"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      
      - name: Run tests
        run: python --version
        run: uv run pytest